config/routes.rb
ShortenUrl::Application.routes.draw do

  scope "/g" do  
    resources :urls, :except => :edit
    get "new_link_form" => 'urls#new_link_from'
  end

  scope "/" do
  	get ":id" => 'urls#redirect'
  end
  root to: 'urls#index'
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :url

  scope :random , order: "RANDOM()"
  validates :address, :format => URI::regexp(%w(http https))

end

app/models/url.rb
class Url < ActiveRecord::Base
	has_many :links
	validates :access_token, :uniqueness => true
	accepts_nested_attributes_for :links, :allow_destroy => true, :reject_if => :all_blank
	validate :links_presence?


	def access_token_set
		token = generate
		unless Url.exists?( :access_token => token)
			self.access_token = token
		else
			access_token_set
		end
	end

	def generate
		require 'securerandom'
		s = SecureRandom.urlsafe_base64(6)
	end

	private
	def links_presence?
		errors.add(:links, "can't be blank") if links.blank?
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :set_url, only: [:update, :destroy]
  before_action :set_access_token, only: [:edit, :show]

  # GET /urls
  # GET /urls.json
  def index
    @url = Url.new
    @links = [@url.links.build]
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
  end

  # GET /urls/new
  def new
    @url = Url.new
    @links = [@url.links.build]
  end

  # GET /urls/1/edit
  def edit
    @links = @url.links
  end

  def redirect
    @url = Url.find_by(access_token: params[:id])
    link = @url.links.random.first
    link.update( count: link.count + 1)
    redirect_to "#{link.address}"
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)
    @url.access_token_set

    respond_to do |format|
      if @url.save
        format.html { redirect_to url_path(@url.access_token), notice: '短縮URLを作成しました。' }
        format.json { render action: 'show', status: :created, location: @url }
      else
         @links =  (@url.links.blank? ? [@url.links.build] : @url.links)

        format.html { render action: 'new' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /urls/1
  # PATCH/PUT /urls/1.json
  def update
    respond_to do |format|
      if @url.update(url_params)
        format.html { redirect_to @url, notice: 'Url was successfully updated.' }
        format.json { head :no_content }
      else
        @links =  (@url.links.blank? ? [@url.links.build] : @url.links)
        format.html { render action: 'edit' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url.destroy
    respond_to do |format|
      format.html { redirect_to urls_url }
      format.json { head :no_content }
    end
  end

  def new_link_form
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    def set_access_token
       @url = Url.find_by( access_token: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:links_attributes => [:id , :address, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def link_to_add_fields(name, f, association)
	    new_object = f.object.class.reflect_on_association(association).klass.new
	    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
	      render("fields_new_" + association.to_s.singularize, :l => builder)
	 	end
		link_to_function(name, raw("add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")"), :class => "btn")
	end

	def link_to_remove_fields(name, f)
    	f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
	end
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ShortenUrl</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="container-narrow">
		<div class="masthead">
			<h3 class="muted"><a href="/">URL shortening</a></h3>
		</div>
		<%= yield %>

		      <div class="footer">
        <p>&copy; URL shortening 2013</p>
      </div>

	</div>

</body>
</html>

app/views/urls/_fields_new_link.html.erb
<div class="fields control-group">
	<div class="field">
		<div class="control-label"><%= l.label :address, "リンク先" %></div>
		<div class="controls">
			<%= l.text_field :address, placeholder: "http://example.com" %>　 <%= link_to_remove_fields "削除", l %>
		</div>
	</div>
</div>

app/views/urls/_form.html.erb
<%= form_for(@url, url: (@url.new_record?? urls_path : url_path(@url))) do |f| %>
<% if @url.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

  <ul>
    <% @url.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="form-horizontal" >
  <% @links.each_with_index do |link , i| %>
  <%= f.fields_for :links, link, :child_index => i do |l| %>
  <%= render :partial => 'fields_new_link', :locals => { :link => link, :l => l, :i => i} %>
  <% end %>
  <% end %>
  <div class="media">
    <div class="pull-left">
      <%= link_to_add_fields "リンク先を追加する", f, :links %>
    </div>
    <div class="actions pull-right">
      <%= f.submit "短縮URLを作る", :class => "btn btn-success" %>
    </div>
  </div>
</div>
<% end %>

app/views/urls/edit.html.erb
      <hr>
      <div class="jumbotron">
        <h1>URL shortening</h1>
      </div>

<div class="well">
<h2 class="top-header">リンク先編集画面</h2>
<%= render "form" %>
<div class="media" >
<%= link_to '戻る', url_path(@url.access_token) , :class => "btn pull-right" %>
</div>

</div>

app/views/urls/index.html.erb
      <hr>
      <div class="jumbotron">
        <h1>URL shortening</h1>
        <p class="lead">「URL shortening」はsplitテストのできる短縮URLサービスです。<br />リンク先を複数設定すれば、１つの短縮URLでランダムにリンク先を飛ばすことができます。</p>
      </div>

<div class="well">
<h2 class="top-header">リンク先を入力してください</h2>
<%= render "form" %>
</div>

app/views/urls/new.html.erb
      <hr>
      <div class="jumbotron">
        <h1>URL shortening</h1>
        <p class="lead">「URL shortening」はsplitテストのできる短縮URLサービスです。<br />リンク先を複数設定すれば、１つの短縮URLでランダムにリンク先を飛ばすことができます。</p>
      </div>

<div class="well">
<h2 class="top-header">リンク先を入力してください</h2>
<%= render "form" %>
</div>

app/views/urls/show.html.erb
<hr />
<% if notice %>
<div class="alert fade in">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<%= notice %>
</div>
<% end %>

<div class="well">
	<p>
		<strong>作成したURL：　http://<%= request.host %>/<%= @url.access_token %></strong>
	</p>
	<ul>
		<% @url.links.each_with_index do |link, i| %>
		<li>リンク先<%= i +1 %>：　<%= link.address %>　表示回数（<%= link.count %>）</li>
		<% end %>
	</ul>
	<div class="media">
		<div class="pull-right">
			<%= link_to 'TOPへ戻る', root_path , :class => "btn" %>　
		</div>
	</div>

</div>